import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const tariffs = [['1 час', '1200 тг', 'Классический игровой слот'], ['2+1 пакет', '3000 тг', '3 часа по цене 2'], ['Открытый счет', 'от 1200 тг', 'Играйте в своем ритме']];
function formatPhone(value) { const digits = value.replace(/\D/g, '').replace(/^8/, '7').replace(/^7/, '').slice(0, 10); const area = digits.slice(0, 3); const first = digits.slice(3, 6); const second = digits.slice(6, 8); const last = digits.slice(8, 10); let result = '+7'; if (digits.length) result += ` (${area}`; if (digits.length >= 3) result += ')'; if (digits.length > 3) result += ` ${first}`; if (digits.length >= 6) result += ` ${second}`; if (digits.length >= 8) result += ` ${last}`; return result; }
async function api(url, options = {}) { const response = await fetch(`/api${url}`, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Ошибка запроса'); return data; }

function App() {
  const [page, setPage] = useState('home'); const [rooms, setRooms] = useState([]); const [news, setNews] = useState([]);
  const [ownerToken, setOwnerToken] = useState(localStorage.getItem('restart-owner-token') || ''); const owner = Boolean(ownerToken); const [reservationRoom, setReservationRoom] = useState(null); const [trackedReservation, setTrackedReservation] = useState(null); const [notice, setNotice] = useState('');
  const refresh = async () => {
    try {
      const [roomData, newsData] = await Promise.all([api('/rooms'), api('/news')]);
      setRooms(roomData);
      setNews(newsData);
    } catch (error) {
      setNotice(error.message);
    }
  };
  useEffect(() => { refresh(); const timer = setInterval(refresh, 15000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (!trackedReservation) return undefined; const checkStatus = async () => { try { const result = await api(`/reservations/${trackedReservation.id}/status?token=${encodeURIComponent(trackedReservation.token)}`); if (result.status === 'approved') { setNotice('Бронь подтверждена владельцем. Ждём вас в RESTART!'); setTrackedReservation(null); } else if (result.status === 'rejected') { setNotice('Владелец отклонил эту заявку. Выберите другое время или зал.'); setTrackedReservation(null); } } catch { setTrackedReservation(null); } }; checkStatus(); const timer = setInterval(checkStatus, 5000); return () => clearInterval(timer); }, [trackedReservation]);
  const showNotice = (message) => { setNotice(message); window.setTimeout(() => setNotice(''), 4200); };
  const submitReservation = async (form) => {
    try {
      const reservation = await api('/reservations', { method: 'POST', body: JSON.stringify({ ...form, roomId: reservationRoom }) });
      setTrackedReservation({ id: reservation.id, token: reservation.clientToken });
      setReservationRoom(null);
      showNotice('Заявка отправлена. Статус обновится после решения владельца.');
    } catch (error) {
      showNotice(error.message);
    }
  };
  return <><Header page={page} setPage={setPage} owner={owner} /><main>{page === 'home' && <Home setPage={setPage} rooms={rooms} tariffs={tariffs} setReservationRoom={setReservationRoom} />}{page === 'news' && <News news={news} />}{page === 'monitor' && <Monitor rooms={rooms} setReservationRoom={setReservationRoom} />}{page === 'owner' && owner && <Owner token={ownerToken} showNotice={showNotice} refresh={refresh} />}{page === 'owner' && !owner && <Login onLogin={(token) => { setOwnerToken(token); localStorage.setItem('restart-owner-token', token); }} />}</main><Footer />{reservationRoom && <ReservationModal roomId={reservationRoom} close={() => setReservationRoom(null)} submit={submitReservation} />}{notice && <div className="toast">{notice}</div>}</>;
}
function Header({ page, setPage, owner }) { const nav = [['home', 'Главная'], ['news', 'Новости'], ['monitor', 'Онлайн монитор']]; return <header className="topbar"><button className="brand" onClick={() => setPage('home')}><span className="brand-mark">◉</span><span>RESTART <b>PS CLUB</b></span></button><nav>{nav.map(([id, label]) => <button className={page === id ? 'active' : ''} key={id} onClick={() => setPage(id)}>{label}</button>)}<button className="owner-link" onClick={() => setPage('owner')}>{owner ? 'Панель владельца' : 'Владелец'}</button></nav></header>; }
function Home({ setPage, rooms, tariffs, setReservationRoom }) { return <div className="page home-page"><section className="hero"><div className="hero-copy"><p className="eyebrow">ALMATY · PS5 LOUNGE</p><h1>Играй громко.<br /><em>Отдыхай красиво.</em></h1><p className="hero-text">Премиальный игровой клуб для тех, кто ценит хороший матч, удобный зал и атмосферу, в которую хочется возвращаться.</p><div className="hero-actions"><button className="button primary" onClick={() => setPage('monitor')}>Проверить VIP залы <span>→</span></button><button className="button ghost" onClick={() => setPage('news')}>Что нового</button></div><div className="hours"><span className="status-dot" />Открыты ежедневно <b>15:00 — 03:00</b></div></div><div className="hero-console"><div className="console-light" /><div className="console"><div className="console-disc" /><div className="console-line" /></div><div className="controller"><i /><i /><div className="sticks" /><div className="buttons">× ○ △ □</div></div><div className="float-label"><strong>01</strong><span>Место, где<br />побеждают</span></div></div></section><section className="section intro"><div><p className="eyebrow">RESTART PLAYSTATION CLUB</p><h2>Твоя игра.<br /><span>Твой ритм.</span></h2></div><p>4 VIP-зала, актуальный онлайн-мониторинг и бронирование с подтверждением владельца. Всё необходимое для сильного вечера в одном месте.</p></section><section className="section"><div className="section-heading"><div><p className="eyebrow">ПРАЙС-ЛИСТ</p><h2>Простые условия</h2></div><span className="section-number">01 / 03</span></div><div className="tariff-grid">{tariffs.map(([name, price, sub], index) => <article className="tariff" key={name}><span className="tariff-index">0{index + 1}</span><h3>{name}</h3><p>{sub}</p><strong>{price}</strong></article>)}</div></section><section className="section mini-monitor"><div><p className="eyebrow">LIVE STATUS</p><h2>Выбери свой VIP</h2><p>Статус залов обновляется автоматически. Забронировать можно любой свободный зал.</p></div><div className="room-strip">{rooms.map((room) => <button key={room.id} className={`room-chip ${room.status}`} onClick={() => setReservationRoom(room.id)}><span>VIP {String(room.id).padStart(2, '0')}</span><small>{room.status === 'free' ? 'Свободен' : 'Занят'}</small></button>)}</div></section><section className="address"><div><p className="eyebrow">COME THROUGH</p><h2>Суюнбая, 33/1<br /><span>2 этаж</span></h2></div><a href="https://go.2gis.com/ZAf5N" target="_blank" rel="noreferrer">Открыть в 2GIS <span>↗</span></a></section></div>; }
function News({ news }) { return <div className="page simple-page"><div className="page-title"><p className="eyebrow">UPDATES</p><h1>Новости клуба</h1><p>Следи за новыми турнирами, событиями и специальными предложениями RESTART.</p></div>{news.length === 0 ? <div className="empty-state"><span>✦</span><h2>Пока тихо</h2><p>Здесь скоро появятся новости клуба.</p></div> : <div className="news-grid">{news.map((item) => <article className="news-card" key={item.id}><span>{item.date}</span><h2>{item.title}</h2><p>{item.text}</p></article>)}</div>}</div>; }
function Monitor({ rooms, setReservationRoom }) { return <div className="page simple-page"><div className="page-title split-title"><div><p className="eyebrow">REAL-TIME AVAILABILITY</p><h1>Онлайн монитор</h1><p>Актуальный статус VIP-залов клуба.</p></div><div className="live-pill"><span className="status-dot" />LIVE · обновляется автоматически</div></div><div className="rooms-grid">{rooms.map((room) => <RoomCard key={room.id} room={room} onReserve={() => setReservationRoom(room.id)} />)}</div><div className="monitor-note"><span>i</span><p>Заявка на бронь отправляется владельцу клуба. Зал закрепляется за вами только после подтверждения.</p></div></div>; }
function RoomCard({ room, onReserve }) { const [left, setLeft] = useState(Math.max(0, (room.occupiedUntil || Date.now()) - Date.now())); useEffect(() => { const id = setInterval(() => setLeft(Math.max(0, (room.occupiedUntil || Date.now()) - Date.now())), 1000); return () => clearInterval(id); }, [room.occupiedUntil]); const time = `${String(Math.floor(left / 3600000)).padStart(2, '0')}:${String(Math.floor(left / 60000) % 60).padStart(2, '0')}:${String(Math.floor(left / 1000) % 60).padStart(2, '0')}`; return <article className={`room-card ${room.status}`}><div className="room-card-top"><span className="room-label">VIP {String(room.id).padStart(2, '0')}</span><span className="room-status"><i />{room.status === 'free' ? 'СВОБОДЕН' : 'ЗАНЯТ'}</span></div><div className="room-visual"><span>PS5</span><strong>{String(room.id).padStart(2, '0')}</strong></div>{room.status === 'busy' ? <div className="timer"><small>Освободится через</small><b>{time}</b></div> : <div className="timer"><small>Можно забронировать</small><b>сейчас</b></div>}<button className="button room-button" onClick={onReserve}>{room.status === 'free' ? 'Поставить бронь' : 'Запросить бронь'} <span>→</span></button></article>; }
function ReservationModal({ roomId, close, submit }) { const [form, setForm] = useState({ name: '', phone: '', time: '' }); return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); submit(form); }}><button type="button" className="close" onClick={close}>×</button><p className="eyebrow">REQUEST A RESERVATION</p><h2>Поставить бронь</h2><p className="modal-sub">Оставьте номер для связи. Владелец подтвердит бронь на сайте и сможет вам позвонить.</p><label>ИМЯ<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Как к вам обращаться?" /></label><label>ТЕЛЕФОН<input required type="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: formatPhone(e.target.value) })} placeholder="+7 (___) ___ __ __" /></label><label>VIP ЗОНА<select value={roomId} disabled><option>VIP {String(roomId).padStart(2, '0')}</option></select></label><label>ВРЕМЯ<input required type="time" value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })} /></label><button className="button primary" type="submit">Отправить запрос <span>→</span></button></form></div>; }
function Login({ onLogin }) { const [login, setLogin] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); return <div className="page auth-page"><form className="auth-card" onSubmit={async (event) => { event.preventDefault(); try { const result = await api('/auth/login', { method: 'POST', body: JSON.stringify({ login, password }) }); onLogin(result.token); } catch (e) { setError(e.message); } }}><p className="eyebrow">PRIVATE ACCESS</p><h1>Панель владельца</h1><p>Управление бронями, залами и новостями клуба.</p><label>ЛОГИН<input required value={login} onChange={(e) => setLogin(e.target.value)} /></label><label>ПАРОЛЬ<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <div className="form-error">{error}</div>}<button className="button primary" type="submit">Войти в панель <span>→</span></button></form></div>; }
function Owner({ token, showNotice, refresh }) { const [reservations, setReservations] = useState([]); const [title, setTitle] = useState(''); const [text, setText] = useState(''); const headers = { Authorization: `Bearer ${token}` }; const load = () => api('/reservations', { headers }).then(setReservations); useEffect(() => { load(); }, []); const update = async (id, status) => { await api(`/reservations/${id}`, { method: 'PATCH', headers, body: JSON.stringify({ status }) }); load(); refresh(); showNotice(status === 'approved' ? 'Бронь подтверждена.' : 'Бронь отклонена.'); }; const addNews = async (e) => { e.preventDefault(); await api('/news', { method: 'POST', headers, body: JSON.stringify({ title, text }) }); setTitle(''); setText(''); refresh(); showNotice('Новость опубликована.'); }; return <div className="page owner-page"><div className="page-title split-title"><div><p className="eyebrow">OWNER CONTROL</p><h1>Панель управления</h1><p>Приватная зона RESTART. Здесь видны только запросы владельца.</p></div><div className="owner-badge">● Владелец авторизован</div></div><div className="owner-columns"><section className="owner-panel"><div className="panel-heading"><h2>Запросы на бронь</h2><span>{reservations.filter((item) => item.status === 'pending').length} новых</span></div>{reservations.length === 0 ? <div className="panel-empty">Новых запросов пока нет.</div> : reservations.map((item) => <div className="reservation-row" key={item.id}><div><strong>{item.name}</strong><span>VIP {String(item.roomId).padStart(2, '0')} · {item.time}</span></div><div className="reservation-actions">{item.status === 'pending' ? <><button className="approve" onClick={() => update(item.id, 'approved')}>Подтвердить</button><button className="reject" onClick={() => update(item.id, 'rejected')}>Отклонить</button></> : <span className={`decision ${item.status}`}>{item.status === 'approved' ? 'Подтверждено' : 'Отклонено'}</span>}</div></div>)}</section><section className="owner-panel"><div className="panel-heading"><h2>Добавить новость</h2></div><form onSubmit={addNews} className="news-form"><label>ЗАГОЛОВОК<input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Например: Турнир FIFA" /></label><label>ТЕКСТ<textarea required value={text} onChange={(e) => setText(e.target.value)} placeholder="Расскажите гостям клуба..." /></label><button className="button primary" type="submit">Опубликовать <span>→</span></button></form></section></div></div>; }
function Footer() { return <footer><span>© 2026 RESTART PS CLUB</span><span>Суюнбая 33/1 · Алматы</span><span>Ежедневно 15:00 — 03:00</span></footer>; }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);